### ISSUE TITLE
Use cgov-react-app-playground workflow

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#153]
### Issue description
> **ESTIMATE** 2

See for reasons at https://github.com/NCIOCPL/cgov-react-app-playground/issues/51.

This task should just be making the workflow:
```
name: Workflow
on: [push, pull_request]
jobs:
  react-app-workflow:
    uses: nciocpl/cgov-react-app-playground/.github/workflows/workflow.yml@<tag>
    secrets: inherit
```
