### ISSUE TITLE
Limit workflow runs on push

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#167]
### Issue description
> **ESTIMATE** TBD

Right now each PR requires 2 full workflow runs, one for the push and one for the pull request. Almost all pull requests are from a ticket branch, which we never look at on react-app-dev. Additionally multiple jobs running at the same time will impact performance. Change the `on:` section in the workflow to be:
```
on:
  push:
    branches:
      - master
      - main
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
      - 'prototype/**'
    tags:
      - '*'
  pull_request:
```
(Yes, `pull_request:` has nothing under it.)

See https://github.com/NCIOCPL/cgov-react-app-playground/issues/80 for the same info.
