### ISSUE TITLE
Implement OCPL Configuration Management Standards Check for pull requests

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#168]
### Issue description
> **ESTIMATE** TBD

We now have a GitHub reusable workflow named OCPL Configuration Management Standards Check that will ensure our commit messages match `(#1234) Short description`. This should be added as a workflow to the app for all pull requests SEPARATE from the main CI workflow. The file below should do the job.

`ocpl_cm_standards_check.yml`
```
name: OCPL Configuration Management Standards Check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  commitlint_remote:
    uses: nciocpl/.github/.github/workflows/ocpl_cm_standards_check.yml@workflow/v1
```

See https://github.com/NCIOCPL/cgov-react-app-playground/issues/82 for the same information.
